services:
  fcg-notificationsapi:
    build:
      context: .
      dockerfile: fcg-PaymentsAPI/Dockerfile
    container_name: fcg-paymentsapi
    ports:
      - "8084:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
