apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: notifications-api:latest # Altere para sua imagem (ex: seu-dockerhub/notifications-api:v1)
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RabbitMq__HostName
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: hostname
        - name: RabbitMq__Port
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: port
        - name: RabbitMq__UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: RabbitMq__VirtualHost
          value: "/"
