apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: fcg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: fcg-notifications-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: RabbitMq__HostName
          value: rabbitmq
        - name: RabbitMq__Port
          value: "5672"
        - name: RabbitMq__UserName
          value: guest
        - name: RabbitMq__Password
          value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
  namespace: fcg-system
spec:
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30002
  type: NodePort
